### ISSUE TITLE
大佬地址愿意公开使用不？把它加入ReplaceGoogleCDN备用候选地址

### ISSUE THREAD

**Issue by jingjingxyk** [pansong291/js-lib#1]
ReplaceGoogleCDN备用候选地址规则候选项 https://github.com/justjavac/ReplaceGoogleCDN/tree/master/extension/rules/mirrors

https://github.com/justjavac/ReplaceGoogleCDN/tree/master/extension/rules

**Comment by jingjingxyk** [comment]
以下待合并的规则： https://github.com/jingjingxyk/ReplaceGoogleCDN/pull/17/files

**Comment by pansong291** [comment]
@jingjingxyk 
我不是原作者，我只是使用别人的服务，你可以联系这个博主 https://blog.csdn.net/weixin_40034633/article/details/125491662

我认为他应该会同意的吧

**Comment by jingjingxyk** [comment]
> @jingjingxyk 我不是原作者，我只是使用别人的服务，你可以联系这个博主 https://blog.csdn.net/weixin_40034633/article/details/125491662
> 
> 我认为他应该会同意的吧

已经完成了哈
